Hit the api
BahirHakimy/Leader-boards pull request #2
Opened 2023-03-08 19:16 UTC by BahirHakimy

## In this exercise, according to the requirements described [here](https://github.com/microverseinc/curriculum-javascript/blob/main/leaderboard/m2_send_receive_data.md) I have added the following features.
- Added functions for creating a game, adding scores and getting all scores from the API
- Used `Arrow functions` to implement the functionalities.
- Added functionality for the refresh button.
- Used `async/await` for functions implementation.

2023-03-08 20:09 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @BahirHakimy :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 20:09 UTC, HAMMAS-SALEEM commented on src/index.js
>    const form = $('#addForm');
- [ ] Kindly turn your function to arrow functions because it is a requirement of your project to use arrow functions and secondly to follow ES6 :blush: ES6 arrow functions are more strong than functions with the function keyword :thinking: After turning your function into arrow function it will look like below :arrow_down:

```javascript
const init = async () => {
  const form = $('#addForm');
```

2023-03-08 20:09 UTC, HAMMAS-SALEEM commented on src/modules/getScores.js
> +};
![image](https://user-images.githubusercontent.com/93039359/223829274-cabc31fc-a3ef-4815-8741-ac037ae20e23.png)

- [ ] It would be nice if you add you fix your live link because now it is not taking me to deployed version of your application but it is taking me to somewhere else :fearful: Kindly check it and fix it to make your readme file descriptive, professional and with correct information :+1:

2023-03-08 20:52 UTC, huseyinbiyik requested changes
Hi @BahirHakimy 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- Linter set up well and checks pass 🟢
- Git flow followed 👌
- .gitignore used to ignore requested files 📁
- Commit messages are meaningful and written in imperative tense 📝
- PR description is descriptive 📝


 ## Required Changes ♻️
- Since there is no change on utils.js file I can't pick the lines, as the previous reviewer requested, kindly make sure you use es6 arrow functions for all of your functions 👍 
<img width="1107" alt="Screenshot 2023-03-08 at 11 53 23 PM" src="https://user-images.githubusercontent.com/25887253/223847376-e958d266-338b-4597-aa3c-369a360f6b2d.png">

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 20:59 UTC, BahirHakimy commented
> Hi @BahirHakimy
> 
> Great work on making the changes requested by a previous reviewer 👏 You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. ![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif) [ ![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif) ](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif) [ ](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)
> 
> ## Highlights
> * Linter set up well and checks pass 🟢
> * Git flow followed 👌
> * .gitignore used to ignore requested files 📁
> * Commit messages are meaningful and written in imperative tense 📝
> * PR description is descriptive 📝
> 
> ## Required Changes ♻️
> * Since there is no change on utils.js file I can't pick the lines, as the previous reviewer requested, kindly make sure you use es6 arrow functions for all of your functions 👍
> 
> <img alt="Screenshot 2023-03-08 at 11 53 23 PM" width="1107" src="https://user-images.githubusercontent.com/25887253/223847376-e958d266-338b-4597-aa3c-369a360f6b2d.png">
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._



> Hi @BahirHakimy
> 
> Great work on making the changes requested by a previous reviewer 👏 You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. ![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif) [ ![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif) ](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif) [ ](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)
> 
> ## Highlights
> * Linter set up well and checks pass 🟢
> * Git flow followed 👌
> * .gitignore used to ignore requested files 📁
> * Commit messages are meaningful and written in imperative tense 📝
> * PR description is descriptive 📝
> 
> ## Required Changes ♻️
> * Since there is no change on utils.js file I can't pick the lines, as the previous reviewer requested, kindly make sure you use es6 arrow functions for all of your functions 👍
> 
> <img alt="Screenshot 2023-03-08 at 11 53 23 PM" width="1107" src="https://user-images.githubusercontent.com/25887253/223847376-e958d266-338b-4597-aa3c-369a360f6b2d.png">
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hi @HAMMAS-SALEEM, 
Thanks for your kind reviews, but that file contains utility functions and it's not part of the main application code, so I think I am free on deciding how kind of functions would I use on that. I already noticed that as the previous reviewer suggested, but that is not part main application functionalities and it doesn't make a difference whether I use `arrow functions` or regular functions

2023-03-08 21:08 UTC, BahirHakimy commented
> Hi @huseyinbiyik, Thanks for your kind reviews, but that file contains utility functions and it's not part of the main application code, so I think I am free on deciding how kind of functions would I use on that. I already noticed that as the previous reviewer suggested, but that is not part of the main application functionalities and it doesn't make a difference whether I use `arrow functions` or regular functions for that

I will also face some Linters issues when refactoring to arrow function 
![image](https://user-images.githubusercontent.com/73453971/223850340-5c8d3f44-8485-436b-94f8-dc5e716cd758.png)

2023-03-08 21:28 UTC, Kamba56 approved these changes
Hi @BahirHakimy, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
## Highlights
- [x] All linters passed!👏👏👏
- [x] Great use of Github workflow!👏👏👏
- [x] Descriptive PR!👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 21:29 UTC, merged

2023-05-29 20:43 UTC, BahirHakimy commented on src/modules/getScores.js
> +};
Thanks for your kind review @HAMMAS-SALEEM 
I will fix the issue 😃

2023-05-29 20:44 UTC, BahirHakimy commented on src/index.js
>    const form = $('#addForm');
Thanks for guiding @HAMMAS-SALEEM , I will make the changes 💯